server:
  port: 8080

spring:
  application:
    name: backend-service
  profiles:
    active: @spring.profile.active@

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO