spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5432/Ecommerce-Clothes
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: Ecommerce-clothes
    title: Ecommerce-clothes
    version: v1.0.0
    server: http://localhost:8080

jwt:
  expiryMinutes: 60
  expiryHours: 1
  accessKey: ZkhUi2vh1/T8jai2Pf/cobaYKNt3s9BSpNiVxxDHFFc=
  refreshKey: Y3/2suaJmXxK46fPNMZ45DsGATYokKTo9/3vKgbns1A=
